//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popflex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Popflex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.6 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-ali [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container&quot;&gt;
        ///
        ///    &lt;div align=&quot;center&quot;&gt;
        ///        &lt;table style=&quot;width: 100%&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td width=&quot;100%&quot; style=&quot;font-size: large;&quot; align=&quot;center&quot;&gt;&lt;b&gt;Program Compliant Tag Manifest&lt;/b&gt;&lt;/td&gt;
        ///                &lt;!--&lt;td rowspan=&quot;2&quot;&gt;&lt;img class=&quot;pull-right&quot; alt=&quot;USDA&quot; width=&quot;100&quot; align=&quot;right&quot; src=&quot;data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAUQAA/+4AJkFkb2JlAGTAAAAAAQMAFQQDBgoNAAAY0QAAMXwAAEYBAABjVf/bAIQAAgICAgICAgICAgMCAgIDBAMCAgMEBAQEBAQEBAYEBQUFBQQGB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string salesOrderBody {
            get {
                return ResourceManager.GetString("salesOrderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///thead th {
        ///  text-transform: uppercase;    
        ///}
        ///
        ///td.secondary-header {
        ///    font-weight:bold;
        ///    align-content:center;
        ///}
        ///
        ///td.bolding{
        ///    font-weight:bold;
        ///    padding-right:3em;
        ///}
        ///
        ///table.table-borders {
        ///  border:2px solid black;  
        ///  border-collapse: collapse;
        ///    page-break-inside: avoid;
        ///}
        ///
        ///tr.table-borders {
        ///  border:2px solid black;  
        ///  border-collapse: collapse;
        ///    page-break-inside: avoid;
        ///}
        ///
        ///td.table-borders {
        ///  border:2px solid black;  
        ///  border-collapse: collapse;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string salesOrderStyle {
            get {
                return ResourceManager.GetString("salesOrderStyle", resourceCulture);
            }
        }
    }
}
